version: '3'

services:
  # Database
  db:
    image: mysql:${dbversion}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${rootpassword}
      MYSQL_DATABASE: ${database}
      MYSQL_USER: ${userdatabase}
      MYSQL_PASSWORD: ${passworddatabase}
    ports:
      - "3306:3306"
    networks:
      - backend
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:${phpmyadmin}
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ${host}
      PMA_PORT: ${hostport}
      PMA_ARBITRARY: ${aprirtay}
      MYSQL_ROOT_PASSWORD: ${rootpassword}
    networks:
      - backend

networks:
  backend:
volumes:
  db_data: